substitutions:
  name: "econet-hvac"
  device_description: "Communicate with Econet Netork"
  tx_pin: GPIO19
  rx_pin: GPIO22

esphome:
  name: ${name}
  comment: ${device_description}

preferences:
  flash_write_interval: "24h"

esp32:
  board: esp32dev
  framework: 
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:

ota:

logger:
  baud_rate: 0  # Disable UART logger if using UART0 (pins 1,3)
  level: INFO
  tx_buffer_size: 2000

external_components:
  - source: github://Daniel-dev22/esphome-econet
  # - source: components

uart:
  id: uart_0
  baud_rate: 38400
  rx_buffer_size: 1500
  tx_pin: 
    number: ${tx_pin}
  rx_pin:
    number: ${rx_pin}

econet:
  uart: uart_0
  model: "HVAC"
  hvac_wifi_module_connected: false

climate:
  - platform: econet
    name: "HVAC"

sensor:
  - platform: econet
    cc_hvacmode:
      name: "HVAC Operating Mode"
    cc_spt_stat:
      name: "HVAC Thermostat Temperature"
    cc_coolsetp:
      name: "HVAC Cooling Setpoint"
    cc_automode:
      name: "HVAC Auto Mode"
    cc_rel_hum:
      name: "Thermostat Current Humidity"
    cc_blower_cfm:
      name: "HVAC Air Handler CFM"
    cc_blower_rpm:
      name: "HVAC Air Handler RPM"
    hvac_odu_outside_air_temp:
      name: "HVAC ODU Outside Air Temperature "
    hvac_odu_evaporator_temp:
      name: "HVAC ODU Evaporator Temperature "
    hvac_odu_inverter_crank_speed:
      name: "HVAC ODU Inverter Crank Speed"
    hvac_odu_crankcase_heater_temp:
      name: "HVAC ODU Crankcase Heater Temperature"
    hvac_odu_exv_current_position:
      name: "HVAC ODU Expansion Valve Current Position"
    hvac_odu_exv_super_heat:
      name: "HVAC ODU Expansion Valve Super Heat"
    hvac_odu_suction_line_temp:
      name: "HVAC ODU Suction Line Temp"
    hvac_odu_pressure_suction:
      name: "HVAC ODU Pressure Suction"

text_sensor:
  - platform: econet
    cc_hvacmode_text:
      name: "HVAC Operating Mode Text"
    cc_automode_text:
      name: "HVAC Auto Mode Text"

number:
  - platform: econet
    cc_dhumsetp:
      name: "HVAC Dehumidification Setting Control"
      min_value: 10
      max_value: 80
      step: 1
      mode: 'slider'

switch:
  - platform: econet
    cc_dhum_enable_state:
      name: "HVAC Dehumidification Enable State"
